var vulnerabilities={
  name:"vulnerabilities",
  shortDescribtion:"",
  fullDescribtion:"",
  parts:[
    {name:"heartbleed",describtion:"",recommendation:"",link:""},
    {name:"CCS",describtion:"",recommendation:"",link:""},
    {name:"ticketbleed",describtion:"",recommendation:"",link:""},
    {name:"ROBOT",describtion:"",recommendation:"",link:""},
    {name:"secure_renego",describtion:"",recommendation:"",link:""},
    {name:"secure_client_renego",describtion:"",recommendation:"",link:""},
    {name:"CRIME_TLS",describtion:"",recommendation:"",link:""},
    {name:"BREACH",describtion:"",recommendation:"",link:""},
    {name:"POODLE_SSL",describtion:"",recommendation:"",link:""},
    {name:"fallback_SCSV",describtion:"",recommendation:"",link:""},
    {name:"SWEET32",describtion:"",recommendation:"",link:""},
    {name:"FREAK",describtion:"",recommendation:"",link:""},
    {name:"DROWN",describtion:"",recommendation:"",link:""},
    {name:"DROWN",describtion:"",recommendation:"",link:""},
    {name:"LOGJAM",describtion:"",recommendation:"",link:""},
    {name:"LOGJAM-common_primes",describtion:"",recommendation:"",link:""},
    {name:"BEAST_CBC_TLS1",describtion:"",recommendation:"",link:""},
    {name:"BEAST",describtion:"",recommendation:"",link:""},
    {name:"LUCKY13",describtion:"",recommendation:"",link:""},
    {name:"RC4",describtion:"",recommendation:"",link:""},
  ],
};
module.exports =vulnerabilities;
